name: Deploy Staging
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  issue_comment:
    types: [created, edited, deleted]
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install yarn
        run: npm install -g yarn
      - name: Generate Static File
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          PR_NUMBER=$PR_NUMBER yarn build
      - name: Init new repo in dist folder and commit generated files
        run: |
          cd dist
          git init
          git add -A
          git config --local user.email "laibuithanh.luan@employmenthero.com"
          git config --local user.name "luanlai2201"
          git commit -m 'deploy: $PR_NUMBER'
      - name: Force push to destination branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./docs/dist
